server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

energy:
  producer:
    fixed-rate-ms: 5000
    latitude: 48.2082
    longitude: 16.3738
